import type { Metadata } from "next";
import localFont from "next/font/local"
import 'app/sass/globals.sass'

const workSans = localFont({
  src: "./fonts/WorkSans-VariableFont_wght.ttf",
  variable: "--work-sans",
  weight: "400 600 700",
});

export const metadata: Metadata = {
  title: "FAQ accordion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${workSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
